# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/m/libseekthermal

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/m/libseekthermal

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"default\" \"dev\" \"doc\" \"gui\" \"udev\" \"utils\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/m/libseekthermal/CMakeFiles /home/m/libseekthermal/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/m/libseekthermal/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named utils_package

# Build rule for target.
utils_package: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 utils_package
.PHONY : utils_package

# fast build rule for target.
utils_package/fast:
	$(MAKE) -f CMakeFiles/utils_package.dir/build.make CMakeFiles/utils_package.dir/build
.PHONY : utils_package/fast

#=============================================================================
# Target rules for targets named package

# Build rule for target.
package: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 package
.PHONY : package

# fast build rule for target.
package/fast:
	$(MAKE) -f CMakeFiles/package.dir/build.make CMakeFiles/package.dir/build
.PHONY : package/fast

#=============================================================================
# Target rules for targets named utils_package_uninstall

# Build rule for target.
utils_package_uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 utils_package_uninstall
.PHONY : utils_package_uninstall

# fast build rule for target.
utils_package_uninstall/fast:
	$(MAKE) -f CMakeFiles/utils_package_uninstall.dir/build.make CMakeFiles/utils_package_uninstall.dir/build
.PHONY : utils_package_uninstall/fast

#=============================================================================
# Target rules for targets named packages

# Build rule for target.
packages: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 packages
.PHONY : packages

# fast build rule for target.
packages/fast:
	$(MAKE) -f CMakeFiles/packages.dir/build.make CMakeFiles/packages.dir/build
.PHONY : packages/fast

#=============================================================================
# Target rules for targets named dev_package_uninstall

# Build rule for target.
dev_package_uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dev_package_uninstall
.PHONY : dev_package_uninstall

# fast build rule for target.
dev_package_uninstall/fast:
	$(MAKE) -f CMakeFiles/dev_package_uninstall.dir/build.make CMakeFiles/dev_package_uninstall.dir/build
.PHONY : dev_package_uninstall/fast

#=============================================================================
# Target rules for targets named package_uninstall

# Build rule for target.
package_uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 package_uninstall
.PHONY : package_uninstall

# fast build rule for target.
package_uninstall/fast:
	$(MAKE) -f CMakeFiles/package_uninstall.dir/build.make CMakeFiles/package_uninstall.dir/build
.PHONY : package_uninstall/fast

#=============================================================================
# Target rules for targets named packages_uninstall

# Build rule for target.
packages_uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 packages_uninstall
.PHONY : packages_uninstall

# fast build rule for target.
packages_uninstall/fast:
	$(MAKE) -f CMakeFiles/packages_uninstall.dir/build.make CMakeFiles/packages_uninstall.dir/build
.PHONY : packages_uninstall/fast

#=============================================================================
# Target rules for targets named doc_package_install

# Build rule for target.
doc_package_install: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc_package_install
.PHONY : doc_package_install

# fast build rule for target.
doc_package_install/fast:
	$(MAKE) -f CMakeFiles/doc_package_install.dir/build.make CMakeFiles/doc_package_install.dir/build
.PHONY : doc_package_install/fast

#=============================================================================
# Target rules for targets named dev_package

# Build rule for target.
dev_package: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dev_package
.PHONY : dev_package

# fast build rule for target.
dev_package/fast:
	$(MAKE) -f CMakeFiles/dev_package.dir/build.make CMakeFiles/dev_package.dir/build
.PHONY : dev_package/fast

#=============================================================================
# Target rules for targets named utils_package_install

# Build rule for target.
utils_package_install: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 utils_package_install
.PHONY : utils_package_install

# fast build rule for target.
utils_package_install/fast:
	$(MAKE) -f CMakeFiles/utils_package_install.dir/build.make CMakeFiles/utils_package_install.dir/build
.PHONY : utils_package_install/fast

#=============================================================================
# Target rules for targets named packages_install

# Build rule for target.
packages_install: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 packages_install
.PHONY : packages_install

# fast build rule for target.
packages_install/fast:
	$(MAKE) -f CMakeFiles/packages_install.dir/build.make CMakeFiles/packages_install.dir/build
.PHONY : packages_install/fast

#=============================================================================
# Target rules for targets named udev_package_uninstall

# Build rule for target.
udev_package_uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 udev_package_uninstall
.PHONY : udev_package_uninstall

# fast build rule for target.
udev_package_uninstall/fast:
	$(MAKE) -f CMakeFiles/udev_package_uninstall.dir/build.make CMakeFiles/udev_package_uninstall.dir/build
.PHONY : udev_package_uninstall/fast

#=============================================================================
# Target rules for targets named gui_package_install

# Build rule for target.
gui_package_install: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gui_package_install
.PHONY : gui_package_install

# fast build rule for target.
gui_package_install/fast:
	$(MAKE) -f CMakeFiles/gui_package_install.dir/build.make CMakeFiles/gui_package_install.dir/build
.PHONY : gui_package_install/fast

#=============================================================================
# Target rules for targets named package_install

# Build rule for target.
package_install: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 package_install
.PHONY : package_install

# fast build rule for target.
package_install/fast:
	$(MAKE) -f CMakeFiles/package_install.dir/build.make CMakeFiles/package_install.dir/build
.PHONY : package_install/fast

#=============================================================================
# Target rules for targets named gui_package

# Build rule for target.
gui_package: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gui_package
.PHONY : gui_package

# fast build rule for target.
gui_package/fast:
	$(MAKE) -f CMakeFiles/gui_package.dir/build.make CMakeFiles/gui_package.dir/build
.PHONY : gui_package/fast

#=============================================================================
# Target rules for targets named dev_package_install

# Build rule for target.
dev_package_install: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dev_package_install
.PHONY : dev_package_install

# fast build rule for target.
dev_package_install/fast:
	$(MAKE) -f CMakeFiles/dev_package_install.dir/build.make CMakeFiles/dev_package_install.dir/build
.PHONY : dev_package_install/fast

#=============================================================================
# Target rules for targets named default_component

# Build rule for target.
default_component: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 default_component
.PHONY : default_component

# fast build rule for target.
default_component/fast:
	$(MAKE) -f CMakeFiles/default_component.dir/build.make CMakeFiles/default_component.dir/build
.PHONY : default_component/fast

#=============================================================================
# Target rules for targets named udev_package

# Build rule for target.
udev_package: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 udev_package
.PHONY : udev_package

# fast build rule for target.
udev_package/fast:
	$(MAKE) -f CMakeFiles/udev_package.dir/build.make CMakeFiles/udev_package.dir/build
.PHONY : udev_package/fast

#=============================================================================
# Target rules for targets named udev_package_install

# Build rule for target.
udev_package_install: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 udev_package_install
.PHONY : udev_package_install

# fast build rule for target.
udev_package_install/fast:
	$(MAKE) -f CMakeFiles/udev_package_install.dir/build.make CMakeFiles/udev_package_install.dir/build
.PHONY : udev_package_install/fast

#=============================================================================
# Target rules for targets named doc_package_uninstall

# Build rule for target.
doc_package_uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc_package_uninstall
.PHONY : doc_package_uninstall

# fast build rule for target.
doc_package_uninstall/fast:
	$(MAKE) -f CMakeFiles/doc_package_uninstall.dir/build.make CMakeFiles/doc_package_uninstall.dir/build
.PHONY : doc_package_uninstall/fast

#=============================================================================
# Target rules for targets named doc_package

# Build rule for target.
doc_package: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc_package
.PHONY : doc_package

# fast build rule for target.
doc_package/fast:
	$(MAKE) -f CMakeFiles/doc_package.dir/build.make CMakeFiles/doc_package.dir/build
.PHONY : doc_package/fast

#=============================================================================
# Target rules for targets named source_packages

# Build rule for target.
source_packages: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 source_packages
.PHONY : source_packages

# fast build rule for target.
source_packages/fast:
	$(MAKE) -f CMakeFiles/source_packages.dir/build.make CMakeFiles/source_packages.dir/build
.PHONY : source_packages/fast

#=============================================================================
# Target rules for targets named gui_package_uninstall

# Build rule for target.
gui_package_uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gui_package_uninstall
.PHONY : gui_package_uninstall

# fast build rule for target.
gui_package_uninstall/fast:
	$(MAKE) -f CMakeFiles/gui_package_uninstall.dir/build.make CMakeFiles/gui_package_uninstall.dir/build
.PHONY : gui_package_uninstall/fast

#=============================================================================
# Target rules for targets named udev_component

# Build rule for target.
udev_component: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 udev_component
.PHONY : udev_component

# fast build rule for target.
udev_component/fast:
	$(MAKE) -f CMakeFiles/udev_component.dir/build.make CMakeFiles/udev_component.dir/build
.PHONY : udev_component/fast

#=============================================================================
# Target rules for targets named precise_distribution

# Build rule for target.
precise_distribution: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 precise_distribution
.PHONY : precise_distribution

# fast build rule for target.
precise_distribution/fast:
	$(MAKE) -f CMakeFiles/precise_distribution.dir/build.make CMakeFiles/precise_distribution.dir/build
.PHONY : precise_distribution/fast

#=============================================================================
# Target rules for targets named distributions

# Build rule for target.
distributions: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 distributions
.PHONY : distributions

# fast build rule for target.
distributions/fast:
	$(MAKE) -f CMakeFiles/distributions.dir/build.make CMakeFiles/distributions.dir/build
.PHONY : distributions/fast

#=============================================================================
# Target rules for targets named trusty_distribution

# Build rule for target.
trusty_distribution: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 trusty_distribution
.PHONY : trusty_distribution

# fast build rule for target.
trusty_distribution/fast:
	$(MAKE) -f CMakeFiles/trusty_distribution.dir/build.make CMakeFiles/trusty_distribution.dir/build
.PHONY : trusty_distribution/fast

#=============================================================================
# Target rules for targets named gui_component

# Build rule for target.
gui_component: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gui_component
.PHONY : gui_component

# fast build rule for target.
gui_component/fast:
	$(MAKE) -f src/bin/CMakeFiles/gui_component.dir/build.make src/bin/CMakeFiles/gui_component.dir/build
.PHONY : gui_component/fast

#=============================================================================
# Target rules for targets named utils_component

# Build rule for target.
utils_component: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 utils_component
.PHONY : utils_component

# fast build rule for target.
utils_component/fast:
	$(MAKE) -f src/bin/CMakeFiles/utils_component.dir/build.make src/bin/CMakeFiles/utils_component.dir/build
.PHONY : utils_component/fast

#=============================================================================
# Target rules for targets named send

# Build rule for target.
send: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 send
.PHONY : send

# fast build rule for target.
send/fast:
	$(MAKE) -f src/bin/utils/CMakeFiles/send.dir/build.make src/bin/utils/CMakeFiles/send.dir/build
.PHONY : send/fast

#=============================================================================
# Target rules for targets named raw2png

# Build rule for target.
raw2png: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 raw2png
.PHONY : raw2png

# fast build rule for target.
raw2png/fast:
	$(MAKE) -f src/bin/utils/CMakeFiles/raw2png.dir/build.make src/bin/utils/CMakeFiles/raw2png.dir/build
.PHONY : raw2png/fast

#=============================================================================
# Target rules for targets named list

# Build rule for target.
list: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 list
.PHONY : list

# fast build rule for target.
list/fast:
	$(MAKE) -f src/bin/utils/CMakeFiles/list.dir/build.make src/bin/utils/CMakeFiles/list.dir/build
.PHONY : list/fast

#=============================================================================
# Target rules for targets named dump

# Build rule for target.
dump: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dump
.PHONY : dump

# fast build rule for target.
dump/fast:
	$(MAKE) -f src/bin/utils/CMakeFiles/dump.dir/build.make src/bin/utils/CMakeFiles/dump.dir/build
.PHONY : dump/fast

#=============================================================================
# Target rules for targets named capture

# Build rule for target.
capture: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 capture
.PHONY : capture

# fast build rule for target.
capture/fast:
	$(MAKE) -f src/bin/utils/CMakeFiles/capture.dir/build.make src/bin/utils/CMakeFiles/capture.dir/build
.PHONY : capture/fast

#=============================================================================
# Target rules for targets named calibrate

# Build rule for target.
calibrate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 calibrate
.PHONY : calibrate

# fast build rule for target.
calibrate/fast:
	$(MAKE) -f src/bin/utils/CMakeFiles/calibrate.dir/build.make src/bin/utils/CMakeFiles/calibrate.dir/build
.PHONY : calibrate/fast

#=============================================================================
# Target rules for targets named view

# Build rule for target.
view: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 view
.PHONY : view

# fast build rule for target.
view/fast:
	$(MAKE) -f src/bin/gui/CMakeFiles/view.dir/build.make src/bin/gui/CMakeFiles/view.dir/build
.PHONY : view/fast

#=============================================================================
# Target rules for targets named seekthermal

# Build rule for target.
seekthermal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 seekthermal
.PHONY : seekthermal

# fast build rule for target.
seekthermal/fast:
	$(MAKE) -f src/lib/seekthermal/CMakeFiles/seekthermal.dir/build.make src/lib/seekthermal/CMakeFiles/seekthermal.dir/build
.PHONY : seekthermal/fast

#=============================================================================
# Target rules for targets named dev_component

# Build rule for target.
dev_component: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dev_component
.PHONY : dev_component

# fast build rule for target.
dev_component/fast:
	$(MAKE) -f src/lib/seekthermal/CMakeFiles/dev_component.dir/build.make src/lib/seekthermal/CMakeFiles/dev_component.dir/build
.PHONY : dev_component/fast

#=============================================================================
# Target rules for targets named base

# Build rule for target.
base: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 base
.PHONY : base

# fast build rule for target.
base/fast:
	$(MAKE) -f src/lib/seekthermal/base/CMakeFiles/base.dir/build.make src/lib/seekthermal/base/CMakeFiles/base.dir/build
.PHONY : base/fast

#=============================================================================
# Target rules for targets named command

# Build rule for target.
command: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 command
.PHONY : command

# fast build rule for target.
command/fast:
	$(MAKE) -f src/lib/seekthermal/command/CMakeFiles/command.dir/build.make src/lib/seekthermal/command/CMakeFiles/command.dir/build
.PHONY : command/fast

#=============================================================================
# Target rules for targets named aaa

# Build rule for target.
aaa: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 aaa
.PHONY : aaa

# fast build rule for target.
aaa/fast:
	$(MAKE) -f src/lib/seekthermal/models/aaa/CMakeFiles/aaa.dir/build.make src/lib/seekthermal/models/aaa/CMakeFiles/aaa.dir/build
.PHONY : aaa/fast

#=============================================================================
# Target rules for targets named usb

# Build rule for target.
usb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 usb
.PHONY : usb

# fast build rule for target.
usb/fast:
	$(MAKE) -f src/lib/seekthermal/usb/CMakeFiles/usb.dir/build.make src/lib/seekthermal/usb/CMakeFiles/usb.dir/build
.PHONY : usb/fast

#=============================================================================
# Target rules for targets named default_doxygen_html

# Build rule for target.
default_doxygen_html: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 default_doxygen_html
.PHONY : default_doxygen_html

# fast build rule for target.
default_doxygen_html/fast:
	$(MAKE) -f doc/CMakeFiles/default_doxygen_html.dir/build.make doc/CMakeFiles/default_doxygen_html.dir/build
.PHONY : default_doxygen_html/fast

#=============================================================================
# Target rules for targets named doc_component

# Build rule for target.
doc_component: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc_component
.PHONY : doc_component

# fast build rule for target.
doc_component/fast:
	$(MAKE) -f doc/CMakeFiles/doc_component.dir/build.make doc/CMakeFiles/doc_component.dir/build
.PHONY : doc_component/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install"
	@echo "... utils_package"
	@echo "... package"
	@echo "... utils_package_uninstall"
	@echo "... packages"
	@echo "... list_install_components"
	@echo "... dev_package_uninstall"
	@echo "... package_uninstall"
	@echo "... packages_uninstall"
	@echo "... doc_package_install"
	@echo "... dev_package"
	@echo "... install/local"
	@echo "... utils_package_install"
	@echo "... packages_install"
	@echo "... udev_package_uninstall"
	@echo "... gui_package_install"
	@echo "... package_install"
	@echo "... gui_package"
	@echo "... dev_package_install"
	@echo "... default_component"
	@echo "... udev_package"
	@echo "... udev_package_install"
	@echo "... doc_package_uninstall"
	@echo "... doc_package"
	@echo "... source_packages"
	@echo "... gui_package_uninstall"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... udev_component"
	@echo "... precise_distribution"
	@echo "... distributions"
	@echo "... trusty_distribution"
	@echo "... gui_component"
	@echo "... utils_component"
	@echo "... send"
	@echo "... raw2png"
	@echo "... list"
	@echo "... dump"
	@echo "... capture"
	@echo "... calibrate"
	@echo "... view"
	@echo "... seekthermal"
	@echo "... dev_component"
	@echo "... base"
	@echo "... command"
	@echo "... aaa"
	@echo "... usb"
	@echo "... default_doxygen_html"
	@echo "... doc_component"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

